### ISSUE TITLE
项目编译报错

### ISSUE THREAD

**Issue by LeeJunhui** [Josin22/Yuncai#2]
# 如下所示
/Users/leejunhui/Documents/Development/iOS/代码集/iOSSourceCodeKitFromGitHub/Yuncai/YBL365/Class/Profile/Section2/FollowGoods/ViewModel/YBLFollowGoodsStoreService.m:191:17: error: property 'viewModel' not found on object of type 'YBLStoreViewController *'; did you mean 'viewLoaded'?
        storeVC.viewModel = viewModel;
                ^~~~~~~~~
                viewLoaded
In module 'UIKit' imported from Comment/MacroTools/YBLDataMacro.h:11:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIViewController.h:118:58: note: 'viewLoaded' declared here
@property(nonatomic, readonly, getter=isViewLoaded) BOOL viewLoaded NS_AVAILABLE_IOS(3_0);
                                                         ^
/Users/leejunhui/Documents/Development/iOS/代码集/iOSSourceCodeKitFromGitHub/Yuncai/YBL365/Class/Profile/Section2/FollowGoods/ViewModel/YBLFollowGoodsStoreService.m:191:27: error: assignment to readonly property
        storeVC.viewModel = viewModel;
        ~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~

**Comment by Josin22** [comment]
xcode 版本多少

**Comment by LeeJunhui** [comment]
最新的Xcode9.0

**Comment by Josin22** [comment]
看看这个[#5](https://github.com/Josin22/Yuncai/issues/5)
